### PR TITLE
Fix dial-server to support YouTube clients for multiple platforms

### PR DESCRIPTION
**Pull request by m-tukiok**
This patch resolves the difference of Content-type used by YouTube clients for different platforms (iOS / Android / Chrome for Windows)

### CODE REVIEW

**Comment by louaybassbouss** [comment]
why you use body parser? according to DIAL specification, the content-type of the HTTP must be text/plain.  Please refer to the DIAL specification section "6.2.1 Client request" for more details.
You can use launchData  and parse it in the YouTube launch method to check if it is pairing or launch. launchData must be always a UTF-8 string to be inline with the DIAL specification.

**Comment by m-tukiok** [comment]
Actually, if you run chrome v53 on Windows PC or Mac, it is sending POST request with the content-type of HTTP as 'content-type': 'application/x-www-form-urlencoded;charset=UTF-8'. In this case, req.text returns undefined. I think Google should follow the specification, but I also think it is application dependent. It will be appreciated if you can tell me better idea than using body-parser...:(

**Comment by louaybassbouss** [comment]
Ok I think the best and fastest solution is to just add `|| req.is("application/x-www-form-urlencoded")` to this line https://github.com/fraunhoferfokus/peer-dial/blob/master/lib/peer-dial.js#L47 . Then you should get in launchData the body of the POST request. You should parse it in the launch method of YouTube App here https://github.com/fraunhoferfokus/peer-dial/blob/master/test/dial-server.js#L47 to check if it is a launch or pairing request.

**Comment by m-tukiok** [comment]
Great ! It worked without body-parser with your suggestion.
No extra parsing was needed with req.text.
It will be appreciated if you can merge the change with || req.is("application/x-www-form-urlencoded") in peer-dial.js.
Then I can abandon my patch :)

**Comment by m-tukiok** [comment]
ok. I will close this pull request and create a new one with a minimum change.

**Pull request closed without merging**
